apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ja8uk260z-go-gitops
  description: This is GitOps manifest for ja8uk260z-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ja8uk260z-go
    janus-idp.io/tekton: ja8uk260z-go
    backstage.io/kubernetes-id: ja8uk260z-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ja8uk260z-go
